# Generated by Django 3.2 on 2021-04-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256)),
                ("address_1", models.CharField(blank=True, max_length=256)),
                ("address_2", models.CharField(blank=True, max_length=256)),
                ("city", models.CharField(blank=True, max_length=256)),
                ("state", models.CharField(blank=True, max_length=256)),
                ("country", models.CharField(blank=True, max_length=256)),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
                ),
            ],
        ),
    ]
