# Generated by Django 3.2 on 2021-04-13 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_auto_20210413_0119"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetupEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(blank=True, max_length=256)),
                ("link", models.CharField(blank=True, max_length=1024)),
                ("time", models.IntegerField(blank=True, null=True)),
                ("is_online_event", models.BooleanField(default=False)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tracker.meetupgroup",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.location",
                    ),
                ),
            ],
        ),
    ]
