# Generated by Django 3.2 on 2021-04-13 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_meetupevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupgroup",
            name="urlname",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="tracker.groupurlname",
            ),
        ),
    ]
