# Generated by Django 3.2 on 2021-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_auto_20210413_2300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupevent",
            name="duration",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meetupevent",
            name="time",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meetupgroup",
            name="member_count",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
